### ISSUE TITLE
Skip for SNAPSHOTS builds

### ISSUE THREAD

**Issue by TuxCoding** [pie-flavor/promptsign#1]
First of all thank you for this tool. It makes gpg signing a lot easier. 

Now my question. Is possible to skip the signing task for snapshot builds. I don't want to enter the key data every time if I only want to deploy it to a local test server. 

Another solution could be to start a session for 15 minutes. After that time you have to enter the data again.

**Comment by pie-flavor** [comment]
Actually, my third solution was simply to not have `build` depend on `signArchives`. But for some reason, even though I changed that, the plugin still does it. Not sure why.

**Comment by randombyte-developer** [comment]
My approach to disable signing is to just disable the whole plugin: https://github.com/randombyte-developer/byte-items/commit/96e8724a7b29016882f4b48a074cdfe13c722049

**Comment by pie-flavor** [comment]
Fixed in 1.1.0.
