### ISSUE TITLE
Doesn't work anymore after update

### ISSUE THREAD

**Issue by randombyte-developer** [pie-flavor/promptsign#2]
I updated this plugin from 1.0.2 to 1.1.0 in [this commit](https://github.com/randombyte-developer/command-utils/commit/4a37e45a34a6d4baf38ef85e3cf7a54b638a55e0#diff-c197962302397baf3a4cc36463dce5eaR8). Before the update, it asked me to enter the password (the file and 'username' are set in a global gradle properties file). After the update, the prompt doesn't show anymore.
The if condition logic is fine, [this] is definitely executed.

What am I doing wrong?

**Comment by pie-flavor** [comment]
1.1.0 made it not automatically run when build gets run. This was because it was annoying when you just wanted a build for debugging. Simply run signArchives and it will ask for information as normal. In fact, see your own comment for #1.

**Comment by randombyte-developer** [comment]
Ah ok thanks ;)
